### ISSUE TITLE
Error: Cannot find module 'robotjs'

### ISSUE THREAD

**Issue by Lesquishy** [ivanseidel/IAMDinosaur#21]
Here is the Full Error
```
Error: Cannot find module 'robotjs'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Rugby\Desktop\NEAT\IAMDinosaur-master\index.js:1:75)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```
I'm running on windows 10 and I've run out of ideas on what to do to fix it.  Please help.

**Comment by ivanseidel** [comment]
Hi @Lesquishy,

Did you try to run `npm install` inside the project's folder?

**Comment by Lesquishy** [comment]
I did. I then tried running it globally, neither worked.

**Comment by Lesquishy** [comment]
I ran it  this morning and ran into a new problem. A build error.

```
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\Users\Rugby\Desktop\NEAT\IAMDinosaur-master\node_modules\r
obotjs\build\robotjs.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Rugby\AppData\Roaming\npm\no
de_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rugby\\AppDat
a\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "r
ebuild"
gyp ERR! cwd C:\Users\Rugby\Desktop\NEAT\IAMDinosaur-master\node_modules\robotjs

gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rugby\\AppData\\
Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! robotjs@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.3.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the robotjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs robotjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls robotjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Rugby\Desktop\NEAT\IAMDinosaur-master\npm-debug.log
```

**Comment by Lesquishy** [comment]
After extensive work i have got it to launch once. ive run out of time to re test right now but

For other people who may encounter the same problem. I just installed Virtual Studio 2015. a custom install,  While installing go : 
- Common Tools > Visual Studio Dependability Tools Update [Number]
- Programming Languages > Visual C++. Select all of them (bar windows XP)
