### ISSUE TITLE
There is a problem when npm install

### ISSUE THREAD

**Issue by yangzgnay** [ivanseidel/IAMDinosaur#35]
I'm new to npm and Nodejs. The following error occur when I do npm install:

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp

![capture](https://cloud.githubusercontent.com/assets/20162618/19671838/848d241c-9a26-11e6-953e-3d7002a18fc9.PNG)

What should I do to continue it? 

some info:
ubuntu 16.04
node v4.2.6
npm  v3.5.2

**Comment by IOAyman** [comment]
Make sure you have the C++ compiler installed on your system.

```bash
sudo apt install build-essential
```

**Comment by sammaina** [comment]
Also having issues with the installation on Windows (10). Installed G++ and still didn't work
![image](https://cloud.githubusercontent.com/assets/20240402/19743218/1f288696-9bd1-11e6-86f0-b30a1ad2f64b.png)

npm: '3.10.8'

**Comment by IOAyman** [comment]
@sammaina  In your case it's looking for the python executable (Line 2 of the error stack). Please add it to your `%PATH%` variable.

**Comment by yangzgnay** [comment]
@IOAyman  I have gcc installed. The same error is still here. I screen shot the whole message for your reference.
![image](https://cloud.githubusercontent.com/assets/20162618/19749687/cbd94e84-9b9f-11e6-8f8e-18130ac810fd.png)

What possibly can it be? Thanks in advance.

**Comment by yangzgnay** [comment]
@sammaina You can follow the A.3 step of the following link to install python or add python to your PATH. Windows do not have python pre-installed. If you want to install python, please install python 2.7.*, since npm do not support 3.*
http://datastructur.es/sp16/materials/lab/lab1b/lab1b.html#a-windows-setup

**Comment by Adryd** [comment]
Similar happens with macOS, It searches for XCode or CLT but fails and crashes.

**Comment by jotaporras** [comment]
I'm having the same issue in Ubuntu 16.04. I verified that I have C++ compiler and Python 2.7.1 installed and in path. Had Node 4, tried updating to 6.9.1, still didn't work. NPM 3.10.9.

This is my stack running npm install (directory = [...]): 

```

> robotjs@0.3.7 install [...]/IAMDinosaur/node_modules/robotjs
> node-gyp rebuild

make: Entering directory '[...]/IAMDinosaur/node_modules/robotjs/build'
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
cc1plus: warning: command line option ‘-Wbad-function-cast’ is valid for C/ObjC but not for C++
In file included from ../src/keypress.h:6:0,
                 from ../src/robotjs.cc:7:
../src/keycode.h:76:23: fatal error: X11/Xutil.h: No such file or directory
compilation terminated.
robotjs.target.mk:113: recipe for target 'Release/obj.target/robotjs/src/robotjs.o' failed
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
make: Leaving directory '[...]/IAMDinosaur/node_modules/robotjs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-24-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd [...]/IAMDinosaur/node_modules/robotjs
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! robotjs@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.3.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the robotjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs robotjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls robotjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     [...]/IAMDinosaur/npm-debug.log
```
I'm having the same issue in Ubuntu 16.04. I verified that I have C++ compiler and Python 2.7.1 installed and in path. Had Node 4, tried updating to 6.9.1, still didn't work.  NPM 3.10.9.

This is my stack running npm install: 

```

> robotjs@0.3.7 install [...]/IAMDinosaur/node_modules/robotjs
> node-gyp rebuild

make: Entering directory '[...]/IAMDinosaur/node_modules/robotjs/build'
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
cc1plus: warning: command line option ‘-Wbad-function-cast’ is valid for C/ObjC but not for C++
In file included from ../src/keypress.h:6:0,
                 from ../src/robotjs.cc:7:
../src/keycode.h:76:23: fatal error: X11/Xutil.h: No such file or directory
compilation terminated.
robotjs.target.mk:113: recipe for target 'Release/obj.target/robotjs/src/robotjs.o' failed
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
make: Leaving directory '[...]/IAMDinosaur/node_modules/robotjs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-24-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd [...]/IAMDinosaur/node_modules/robotjs
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! robotjs@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.3.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the robotjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs robotjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls robotjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     [...]/IAMDinosaur/npm-debug.log
```

**Comment by sammaina** [comment]
@IOAyman @yangzgnay Thanks it helped. Landed into the same error.
![image](https://cloud.githubusercontent.com/assets/20240402/19865467/6920a456-9fad-11e6-888b-04b6d2fe0d86.png)

**Comment by jotaporras** [comment]
Guys, it seems it's a bug with the robotjs dependency. I updated line 23 of package.json to
`    "robotjs": "^0.4.5",`

and now `npm install` works.

**Comment by yangzgnay** [comment]
@jotaporras 
Still not work on my side after changing `^0.3.7 to ^0.4.5`. The same error appears.

**Comment by jotaporras** [comment]
@yangzgnay Maybe take a look at  https://github.com/octalmage/robotjs/issues/17 ? 
The people there speak about a couple of other dependencies that might be needed. Also consider switching to node 6

**Comment by mercuryw** [comment]
I have problem when npm install. I think it has something to do with Robotjs package. 
I have Visual Studio, python2.7. 
![qq 20161103154854](https://cloud.githubusercontent.com/assets/22850454/19958819/0d182cf6-a1dd-11e6-969e-8d6b5c61191f.png)

Can someone help me? Thanks.

**Comment by EduardoHillebrand** [comment]
Idk but i guess it only works on mac OS.

**Comment by HusainZafar** [comment]
@jotaporras Works for me. Thanks
