### ISSUE TITLE
problems while installing - ubuntu

### ISSUE THREAD

**Issue by Cl3V0r** [ivanseidel/IAMDinosaur#42]
I first installed node.js as described and tried to install this rep with "npm install", but got following error code

npm install

> robotjs@0.3.7 install /home/clemens/Dokumente/IAMDinosaur/node_modules/robotjs
> node-gyp rebuild

make: Verzeichnis „/home/clemens/Dokumente/IAMDinosaur/node_modules/robotjs/build“ wird betreten
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
cc1plus: warning: command line option ‘-Wbad-function-cast’ is valid for C/ObjC but not for C++
../src/robotjs.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE keyToggle(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/robotjs.cc:557:17: warning: ‘down’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    toggleKeyCode(key, down, flags);
                 ^
  CC(target) Release/obj.target/robotjs/src/deadbeef_rand.o
  CC(target) Release/obj.target/robotjs/src/mouse.o
  CC(target) Release/obj.target/robotjs/src/keypress.o
  CC(target) Release/obj.target/robotjs/src/keycode.o
  CC(target) Release/obj.target/robotjs/src/screen.o
  CC(target) Release/obj.target/robotjs/src/screengrab.o
  CC(target) Release/obj.target/robotjs/src/snprintf.o
../src/snprintf.c: In function ‘portable_vsnprintf’:
../src/snprintf.c:557:33: warning: signed and unsigned type in conditional expression [-Wsign-compare]
       size_t n = !q ? strlen(p) : (q-p);
                                 ^
../src/snprintf.c:704:40: warning: signed and unsigned type in conditional expression [-Wsign-compare]
             str_arg_l = !q ? precision : (q-str_arg);
                                        ^
../src/snprintf.c:943:62: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             fast_memset(str+str_l, (zero_padding?'0':' '), (n>avail?avail:n));
                                                              ^
../src/snprintf.c:372:35: note: in definition of macro ‘fast_memset’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:943:74: warning: signed and unsigned type in conditional expression [-Wsign-compare]
             fast_memset(str+str_l, (zero_padding?'0':' '), (n>avail?avail:n));
                                                                          ^
../src/snprintf.c:372:35: note: in definition of macro ‘fast_memset’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:960:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             fast_memcpy(str+str_l, str_arg, (n>avail?avail:n));
                                               ^
../src/snprintf.c:365:35: note: in definition of macro ‘fast_memcpy’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:960:59: warning: signed and unsigned type in conditional expression [-Wsign-compare]
             fast_memcpy(str+str_l, str_arg, (n>avail?avail:n));
                                                           ^
../src/snprintf.c:365:35: note: in definition of macro ‘fast_memcpy’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:969:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             fast_memset(str+str_l, '0', (n>avail?avail:n));
                                           ^
../src/snprintf.c:372:35: note: in definition of macro ‘fast_memset’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:969:55: warning: signed and unsigned type in conditional expression [-Wsign-compare]
             fast_memset(str+str_l, '0', (n>avail?avail:n));
                                                       ^
../src/snprintf.c:372:35: note: in definition of macro ‘fast_memset’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:981:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                         (n>avail?avail:n));
                           ^
../src/snprintf.c:365:35: note: in definition of macro ‘fast_memcpy’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:981:39: warning: signed and unsigned type in conditional expression [-Wsign-compare]
                         (n>avail?avail:n));
                                       ^
../src/snprintf.c:365:35: note: in definition of macro ‘fast_memcpy’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:992:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             fast_memset(str+str_l, ' ', (n>avail?avail:n));
                                           ^
../src/snprintf.c:372:35: note: in definition of macro ‘fast_memset’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:992:55: warning: signed and unsigned type in conditional expression [-Wsign-compare]
             fast_memset(str+str_l, ' ', (n>avail?avail:n));
                                                       ^
../src/snprintf.c:372:35: note: in definition of macro ‘fast_memset’
   { register size_t nn = (size_t)(n); \
                                   ^
../src/snprintf.c:564:19: warning: variable ‘starting_p’ set but not used [-Wunused-but-set-variable]
       const char *starting_p;
                   ^
../src/snprintf.c:369:48: warning: ‘str_arg’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       for (ss=(s), dd=(d); nn>0; nn--) *dd++ = *ss++; } }
                                                ^
../src/snprintf.c:573:19: note: ‘str_arg’ was declared here
       const char *str_arg;      /* string address in case of string argument */
                   ^
  CC(target) Release/obj.target/robotjs/src/MMBitmap.o
  CC(target) Release/obj.target/robotjs/src/xdisplay.o
  SOLINK_MODULE(target) Release/obj.target/robotjs.node
/usr/bin/ld: cannot find -lpng
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
robotjs.target.mk:154: die Regel für Ziel „Release/obj.target/robotjs.node“ scheiterte
make: *** [Release/obj.target/robotjs.node] Fehler 1
make: Verzeichnis „/home/clemens/Dokumente/IAMDinosaur/node_modules/robotjs/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-57-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/clemens/Dokumente/IAMDinosaur/node_modules/robotjs
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! robotjs@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.3.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the robotjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs robotjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls robotjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/clemens/Dokumente/IAMDinosaur/npm-debug.log

**Comment by 0wx** [comment]
dang, this issue openup 4 years later, and also I face the same issue
