### ISSUE TITLE
need help doing npm install

### ISSUE THREAD

**Issue by ghost** [ivanseidel/IAMDinosaur#66]
I am a noob and don't know much. Would it be possible for someone to show me step by step guide to run the npm install on a windows 10 OS? Found this a couple days ago and thought it be nice to see it in action. thanks ahead of time.

**Comment by ImSeaWorld** [comment]
This is for issues with the actual application. But anyway, search for "Node.js Command Prompt" then use the "cd" command to get into the folder that you have IAMDinosaur in. Then follow the instructions. If you're still confused, let me know.

**Comment by 52871299hzy** [comment]
```
C:\Users\think\IAMDinosaur>npm install

> robotjs@0.4.7 install C:\Users\think\IAMDinosaur\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.13.0 runtime=node arch=x64 platform=win32)

C:\Users\think\IAMDinosaur\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\think\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\think\IAMDinosaur\node_modules\robotjs
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\think\AppData\Roaming\npm-cache\_logs\2019-01-31T06_22_33_294Z-debug.log
```
How can I solve this? Is it because of Python3?

**Comment by treboryx** [comment]
> ```
> C:\Users\think\IAMDinosaur>npm install
> 
> > robotjs@0.4.7 install C:\Users\think\IAMDinosaur\node_modules\robotjs
> > prebuild-install || node-gyp rebuild
> 
> prebuild-install WARN install No prebuilt binaries found (target=10.13.0 runtime=node arch=x64 platform=win32)
> 
> C:\Users\think\IAMDinosaur\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Users\think\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> gyp ERR! System Windows_NT 10.0.17763
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\think\IAMDinosaur\node_modules\robotjs
> gyp ERR! node -v v10.13.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the robotjs@0.4.7 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\think\AppData\Roaming\npm-cache\_logs\2019-01-31T06_22_33_294Z-debug.log
> ```
> How can I solve this? Is it because of Python3?

You need to install node 6.11.5

After doing that myself, the installation is successful, but the program doesn't start.
