### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by rpx01** [ivanseidel/IAMDinosaur#73]
I had a problem trying to install, I already researched the error, but I did not find anything! Help me! What should I do?

DebugLog: https://pastebin.com/0z6Bnwpt

../src/snprintf.c:573:19: note: ‘str_arg’ was declared here
       const char *str_arg;      /* string address in case of string argument */
                   ^~~~~~~
  CC(target) Release/obj.target/robotjs/src/MMBitmap.o
  CC(target) Release/obj.target/robotjs/src/xdisplay.o
../src/xdisplay.c: In function ‘setXDisplay’:
../src/xdisplay.c:53:16: warning: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration]
  displayName = strdup(name);
                ^~~~~~
../src/xdisplay.c:53:16: warning: incompatible implicit declaration of built-in function ‘strdup’
  SOLINK_MODULE(target) Release/obj.target/robotjs.node
/usr/bin/x86_64-linux-gnu-ld: não foi possível localizar -lpng
/usr/bin/x86_64-linux-gnu-ld: não foi possível localizar -lz
collect2: error: ld returned 1 exit status
robotjs.target.mk:155: recipe for target 'Release/obj.target/robotjs.node' failed
make: *** [Release/obj.target/robotjs.node] Error 1
make: Leaving directory '/home/rpx001/Downloads/IAMDinosaur-master/node_modules/robotjs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rpx001/Downloads/IAMDinosaur-master/node_modules/robotjs
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-27T03_24_13_201Z-debug.log

DebugLog: https://pastebin.com/0z6Bnwpt

**Comment by mbahiense** [comment]
Just update the dependency version `robotjs` to 0.5.1

**Comment by acaciomartins** [comment]
> Just update the dependency version `robotjs` to 0.5.1

Tks.
